## Convention for importing numpy

In [1]:
import numpy as np

In [10]:
arr = [6, 7, 8, 9]
print(type(arr)) # prints the type of the array

a = np.array(arr)
print(type(a)) # prints class type
print(a.shape) # prints shape of the array
print(a.dtype) # prints the data type
# get the dimension of a with ndim
print(a.ndim)
b = np.array([[1, 2, 3], [4,5,6]])
print(b)
print(b.ndim)
print(b.shape)


<class 'list'>
<class 'numpy.ndarray'>
(4,)
int32
1
[[1 2 3]
 [4 5 6]]
2
(2, 3)


## Inbuilt functions that can be used to initilize numpy

In [11]:
# a 2x3 array with random values
np.random.random((2, 3))

array([[0.60944991, 0.5877317 , 0.571419  ],
       [0.26868832, 0.99436831, 0.1721403 ]])

In [12]:
# a 2x3 array of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# a 2x3 array of ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones(2)

array([1., 1.])

In [17]:
# a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Intra-operability of arrays and scalars

In [19]:
c = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

In [20]:
c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [21]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [22]:
c/d

array([[2.25      , 1.6       , 1.16666667],
       [0.11111111, 0.25      , 0.42857143]])

In [23]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

## Indexing with arrays and usinge arrays for data processing

In [26]:
# The elements in the example arrays above can be accessed by indexing like lists in Python
print(a[0])
print(a[3])
print(b[0,0])
print(b[1, 2])
print(c[0, 1])

6
9
1
6
8.0


In [27]:
# Elements in arrays can also beretrieved by slicing rows and coloumns or a combination of in d[1, 0:2]
e = np.array([[10,11,12],[13, 14, 15],
             [16, 17, 18], [19, 20, 21]])

In [28]:
print(e)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [31]:
# Slicing
print(e[:3, :2])
print(e[2,1])

[[10 11]
 [13 14]
 [16 17]]
17


In [32]:
# There are other advanced methods of indexing which are shown below
# Integer indexing
print(e[[2, 0,3, 1],[2, 1, 0, 2]])

[18 11 19 15]


In [36]:
# boolean indexing meeting a specified condition
print(e[e>15])
print(e[e%2==0])

[16 17 18 19 20 21]
[10 12 14 16 18 20]
