In [2]:
import numpy as np

In [3]:
arr = [6, 7, 8]
print(type(arr))

<class 'list'>


In [4]:
a = np.array(arr)
b = np.array()
print(type(arr))
print(a.shape)
print(a.dtype)
print(a.ndim)

<class 'list'>
(3,)
int32
1


In [5]:
b = np.array([[1, 2, 3],[4, 5, 6]])
print(type(b))
print(b.shape)
print(b.dtype)
print(b.ndim)

<class 'numpy.ndarray'>
(2, 3)
int32
2


In [6]:
np.random.random((2, 3))

array([[0.94771815, 0.33876789, 0.27160988],
       [0.91591602, 0.63602988, 0.95255863]])

In [10]:
np.zeros((2, 3))
#np.zeros(2)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
c = np.array([[9.0,8.0,7.0], [1.0,2.0,3.0]])
d = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

In [16]:
print(c+d)
print(c*d)
print(5/d)
print(c**2)

[[13. 13. 13.]
 [10. 10. 10.]]
[[36. 40. 42.]
 [ 9. 16. 21.]]
[[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]
[[81. 64. 49.]
 [ 1.  4.  9.]]


In [18]:
#Indexing in Arrays
print(c[0][0])

9.0


In [20]:
print(d[0, 0:2])

[4. 5.]


In [22]:
#Boolean indexing
print(c[c>2])

[9. 8. 7. 3.]


In [23]:
print(np.sum(c))

30.0


np.save(np.sum(c))